### ISSUE TITLE
Column names ags.csv

### ISSUE THREAD

**Issue by TiboGeysen** [jgehrcke/covid-19-germany-gae#101]
Do you have a link/dataset to convert the columns names in the ags files? I figured out that they are Landkreis Keys and tried to make my own converter, but every dataset I find is in most cases not sufficient.

For example Landkreiskey 1000 => Flensburg

**Comment by jgehrcke** [comment]
Hey @TiboGeysen -- this is what the file https://github.com/jgehrcke/covid-19-germany-gae/blob/master/ags.json is for!

**Comment by jgehrcke** [comment]
Closing this for now. Would however still appreciate your feedback. Thanks!
