### ISSUE TITLE
Data update frequency

### ISSUE THREAD

**Issue by m-catanese** [jgehrcke/covid-19-germany-gae#121]
Hello, I’m looking at the data by state and the latest date is 25 May. How frequent does the data get refreshed?

**Comment by jgehrcke** [comment]
Hey @m-catanese -- thanks for you question.

May I direct you to https://github.com/jgehrcke/covid-19-germany-gae/issues/93 for a brief discussion about how "recent" RKI data is?

In addition to what's being discussed over there I can add that currently (in the current phase of case evolution in Germany) I update the data files in this repository every ~3 days. In terms of _how_ these numbers evolve and in view of the reporting delay within the RKI data I do think that's reasonable. For a more "sensational" and current view the HTTP API is more "real time"!

I of course appreciate your feedback.

**Comment by jgehrcke** [comment]
Quick update: we're very close to having multiple updates per day in this repository now; all done automatically.
