### ISSUE TITLE
Data update

### ISSUE THREAD

**Issue by m-vollmer** [jgehrcke/covid-19-germany-gae#128]
Hi! Great repo! I was just wondering if you are updating the data any time soon. It is now a week old. Thanks!

**Comment by jgehrcke** [comment]
Thanks for the reminder :) Done in https://github.com/jgehrcke/covid-19-germany-gae/pull/129.

**Comment by jgehrcke** [comment]
Quick update: we're very close to having multiple updates per day in this repository now; all done automatically.
