### ISSUE TITLE
data.csv missing days of data?

### ISSUE THREAD

**Issue by groby** [jgehrcke/covid-19-germany-gae#133]
It looks somewhat incomplete - very obvious around April 8th to April 20th, but other dates as well. Given that RKI did report data for the missing days, is there a reason to exclude it, or is this a simple oversight?

**Comment by jgehrcke** [comment]
Hey @groby -- for the most credible view into the past I recommend consuming `cases-rki-*.csv` and `deaths-rki-*.csv`, quote from the README:

> `cases-rki-*.csv` and `deaths-rki-*.csv`: history, based on Robert Koch-Institut data, most credible view into the past: accounts for Meldeverzug. The historical evolution of data points in here is updated daily based on the (less accessible) RKI ArcGIS system.

They don't have gaps :-).

Hope that helps, feel free to discuss further!

**Comment by groby** [comment]
Ah, got it - thank you!
