### ISSUE TITLE
Thüringen data source link is dead

### ISSUE THREAD

**Issue by thebear8** [jgehrcke/covid-19-germany-gae#144]
[https://corona.thueringen.de/covid-19-bulletin/](https://corona.thueringen.de/covid-19-bulletin/) seems to be [https://corona.thueringen.de/bulletin/](https://corona.thueringen.de/bulletin/) now

**Comment by jgehrcke** [comment]
Thanks! I am going to link https://www.tmasgff.de/covid-19/fallzahlen now.
