### ISSUE TITLE
Saarland data source link is dead

### ISSUE THREAD

**Issue by thebear8** [jgehrcke/covid-19-germany-gae#145]
[https://www.saarland.de/254259.htm/](https://www.saarland.de/254259.htm) seems to be dead. I didn't find any replacement link though.

**Comment by jgehrcke** [comment]
linking https://corona.saarland.de/DE/service/aktuelle-lage/aktuelle-lage_node.html now, thanks!

**Comment by thebear8** [comment]
Nice! Good work btw!
