### ISSUE TITLE
Berlin districts?

### ISSUE THREAD

**Issue by RoyalTS** [jgehrcke/covid-19-germany-gae#176]
With Berlin being in the news more and more, is there any possibility to get numbers separately for each of Berlin's districts?

**Comment by jgehrcke** [comment]
Certainly possible for the RKI-based numbers. Just a little bit of programming work :)

**Comment by RoyalTS** [comment]
Is the only thing that needs to happen here to take out the line at https://github.com/jgehrcke/covid-19-germany-gae/blob/c603db20f55786afd29cb134f51aad59f4f901bc/tools/build-rki-csvs.py#L250?

**Comment by jgehrcke** [comment]
That's certainly part of it, but w/o diving a tiny bit deeper again for a few minutes I can't say with confidence whether that's enough or not. We could keep `11000` _and_ the individual ones, but then we'd have to watch out for the per-row sum to not be skewed.

**Comment by jgehrcke** [comment]
done some work towards this in https://github.com/jgehrcke/covid-19-germany-gae/pull/192 -- data update upcoming.

**Comment by jgehrcke** [comment]
Individual Berlin districts are now in https://github.com/jgehrcke/covid-19-germany-gae/blob/master/cases-rki-by-ags.csv and in https://github.com/jgehrcke/covid-19-germany-gae/blob/master/deaths-rki-by-ags.csv, using their official AGS 11001, 11002, etc. The aggregated total with the artificial AGS 11000 is still there. The sums are corrected for that.

**Comment by jgehrcke** [comment]
Ha, made a mistake when implementing this, leading up to https://github.com/jgehrcke/covid-19-germany-gae/issues/233.
