### ISSUE TITLE
sum_cases column in cases-rki-by-ags.csv

### ISSUE THREAD

**Issue by ViktorGrosch** [jgehrcke/covid-19-germany-gae#203]
I have a different sum in the sum_cases column
The last row (`2020-10-29T17:00:00+0000`) currently has a value of `499694`, the total sum of all columns in this row is `530050`.
Please check it, maybe it's my mistake.

thanks

**Comment by jgehrcke** [comment]
The sum should be correct (when you simply build the sum across all columns you count Berlin twice -- it's represented twice, fine-grained and coarse-grained: https://github.com/jgehrcke/covid-19-germany-gae/issues/176).
