### ISSUE TITLE
AG_RKI_SUMS_QUERY_BASE_URL

### ISSUE THREAD

**Issue by sebkur** [jgehrcke/covid-19-germany-gae#208]
Hi, thanks for this project! I've been reading through your source code and trying to run parts of it. Can you tell me what's supposed to be in the AG_RKI_SUMS_QUERY_BASE_URL variable? Thanks!

**Comment by sebkur** [comment]
OK, got it, you're using the ESRI/ArcGIS API. It wasn't obvious to me, I suspected you would maybe be using the SurvStat interface directly. Nevertheless I guess it would be good to document the 'magic' environment variables used by the scripts.

In this case it would be this right?

    export AG_RKI_SUMS_QUERY_BASE_URL="https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/F"eatureServer/0/query

How about we create a list of all those variables?

**Comment by jgehrcke** [comment]
Thank you for asking!

> https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/F"eatureServer/0/query

Not sure if that would work. I decided to use `Covid19_RKI_Sums` instead of `RKI_COVID19`.

So, for `AG_RKI_SUMS_QUERY_BASE_URL` I've been using `https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Covid19_RKI_Sums/FeatureServer/0/query?` successfully for all these months. I don't want to make this my 'official recommendation with warranty' for everyone who runs that code by themselves, though! :)

**Comment by sebkur** [comment]
Where did you get that Covid19_RKI_Sums link from? (If you can still find out, the number of datasets on the ArcGIS platform from RKI is a bit confusing)

I got  the RKI_COVID19 link from here (https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0) then clicking "APIs" dropdown and selecting the "GeoService" URL.

There's this other dataset (https://www.arcgis.com/home/item.html?id=f10774f1c63e40168479a1feb6c7ca74) where the ArcGIS UI looks a bit different, so there's no API dropdown, just a download link for the CSV. Interesting to note is that the anonymous author from ESRI states in the comments that it is precisely that dataset that the dashboard is using :confused: BTW. that CSV file uses a different column for the "ObjectId" it has "FID" instead.

**Comment by sebkur** [comment]
The source for that "other" data set is https://www.arcgis.com/home/item.html?id=dd4580c810204019a7b8eb3e0b329dd6 
> Aktuell werden die Downloadmöglichkeiten auf dieser Seite überarbeitet. Es kann daher zu Unstimmigkeiten bei den > Datensätzen kommen. Bitte nutzen Sie bei Bedarf für den Download der *.csv diesen alternativen Link: Download der Daten als CSV (*.csv)

**Comment by jgehrcke** [comment]
> Where did you get that Covid19_RKI_Sums link from?

I spent quite a bit of time on that topic back in March, by deep-inspecting the interaction between official dashboards and ArcGIS systems, and by diving into the ArgGIS HTTP query API. I also explored the differences between the various ArcGIS "feature servers" like  `Covid19_RKI_Sums`, `RKI_COVID19` --You could start poking around at https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services -- this system contains ArcGIS feature servers not only for Covid things, but also for Berufsfeuerwehren and THW, etc. :).

**Comment by sebkur** [comment]
> You could start poking around at https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services -- this system contains ArcGIS feature servers not only for Covid things, but also for Berufsfeuerwehren and THW, etc. :).

That is a very interesting link, don't know if I just missed it or if it is indeed difficult to find :)
