### ISSUE TITLE
Daten aktualisieren sich nicht

### ISSUE THREAD

**Issue by Toni-99** [jgehrcke/covid-19-germany-gae#239]
Ich benutze im Moment zwar nur das Feld "recovered", jedoch aktualisiere ich es alle 24 Stunden um 7 Uhr frühs. Heute kam es zum zweiten Mal vor, dass sich die Werte nicht aktualisiert haben.

**Comment by jgehrcke** [comment]
Talking about https://covid19-germany.appspot.com/now?

**Comment by Toni-99** [comment]
Oh yes sorry. Im talking about https://covid19-germany.appspot.com/now.

I took a look on these two fields in your response. Im logging the corona data in an own database to send an update every morning. Today my automatic update send the same "recovered" value as yesterday, so that there are no new "recovered cases".

**Comment by jgehrcke** [comment]
Technically it *is* updated corresponding to the timestamps you see -- and if you don't see the number change then it just means that ZO/RL didn't update the number in their data set.

`recovered` is an inherently blurry metric, though, and I think the actual systematic errors in this metric are dominating any 'updating delay/frequency' that you see. I wouldn't want to rely on this number by itself for any meaningful analysis I think :) But that's of course up to you. In hindsight I almost regret having exposed this number :).

**Comment by jgehrcke** [comment]
Feel free to keep discussing, but I'm closing this for now.

**Comment by jgehrcke** [comment]
Quick update: we're very close to having multiple updates per day in this repository now; all done automatically.
