### ISSUE TITLE
Data updates keep overwriting the newest line instead of appending

### ISSUE THREAD

**Issue by silmaril42** [jgehrcke/covid-19-germany-gae#2669]
If you look at the current RiskLayer CSV files, they contain data for days until `2022-03-06` and the next line is always the most recent date.

It seems the logic that decides if it's a new day (for which a new line should be appended) or if it's an update for the current day (for which the last line should be rewritten) is not working as intended any more.

RKI files are still looking good.

**Comment by jgehrcke** [comment]
After the path #2771 I manually triggered a new update. The daily change plot now looks good again. The RL data files will not be touched anymore (the last data line in those files corresponds to March 6, 2022). 

![Screenshot from 2022-05-04 15-58-15](https://user-images.githubusercontent.com/265630/166697038-8510304b-f2d5-4f9c-af73-542f1354a226.png)
