### ISSUE TITLE
Incorporate new Landkreis-based data sources

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/covid-19-germany-gae#43]
- ZEIT ONLINE have updated their data flow. They now pull data from individual Landkreise. Great! 

- Edit: @coezbek made us aware of a nice crowdsourcing effort coordinated in a gsheet linked here: https://github.com/CSSEGISandData/COVID-19/issues/1008#issuecomment-603397126

- Edit: [risklayer](https://twitter.com/risklayer) uses a crowd-sourcing approach and curates LK-based data in a [gsheet](https://docs.google.com/spreadsheets/d/1wg-s4_Lz2Stil6spQEYFdZaBEp8nWW26gVyfHqvcl8s)

Those data sources are relatively early in the Meldekette, and probably quite credible. Will elaborate in the comments.

**Comment by jgehrcke** [comment]
> Die Daten stammen von den zuständigen Behörden der Landkreise und Bundesländer, die ZEIT ONLINE mehrmals am Tag abruft und hier aktualisiert.

> Da es wegen der Meldekette zu Verzögerungen kommt, fragen wir regelmäßig die bestätigten Fälle der 401 Stadt- und Landkreise direkt ab. Diese spiegeln den aktuellsten Stand in Deutschland am besten wider. Diese Zahlen können daher von anderen Quellen wie dem Robert Koch-Institut (RKI) oder der Johns Hopkins Universität abweichen.

**Comment by jgehrcke** [comment]
![Screenshot from 2020-03-24 13-46-34](https://user-images.githubusercontent.com/265630/77427058-f8ed8a00-6dd5-11ea-904a-6e4c7f74cd69.png)

**Comment by jgehrcke** [comment]
for the country-wide case count this was done in https://github.com/jgehrcke/covid-19-germany-gae/pull/45

**Comment by jgehrcke** [comment]
![Screenshot from 2020-03-24 19-09-44](https://user-images.githubusercontent.com/265630/77462013-be9ae180-6e03-11ea-86fb-0eaa33f83f51.png)

**Comment by jgehrcke** [comment]
--> The crowd-sourced spreadsheet and ZEIT ONLINE both report ~33.400 cases at this current time (~19:15 local time). That's quite promising. I assume that both teams take the same approach, don't copy from each other, and arrive at roughly the same number. If that's true then that's good news.

**Comment by stefan123t** [comment]
Hi Jan-Philip,
I just updated Lisas blog with the following comment and URL from the ESRI server, somehow they have the RKI data per Landkreis. Maybe you could use the URL to persist the Landkreis data per day, so we have the historical data saved for posterity.

Kind regards,
Stefan

_Hi Lisa,
you can get the RKI_Landkreise Feature layer with the following GET request. It contains a description of the Attributes queried plus the data in a JSON document:

https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=cases%20desc&outSR=102100&resultOffset=0&resultRecordCount=1000&cacheHint=true

I do not know how often they update the data or how frequently you will be allowed to query their server for this information, nor how they get the data from RKI anyway. Maybe you could also inquire with RKI directly to get the data somewhere.

Kind regards,
Stefan_

**Comment by jgehrcke** [comment]
Thank you @stefan123t for the message! Please keep an eye on this repo. My plan certainly is to compare history across data sources with fine-grained spatial resolution.

**Comment by stefan123t** [comment]
I just see you already have the ESRI RKI Landkreis Feature Service on record of #46.

If you want I have looked for the LK data on the press release sites of the states, but not all states maintain a history of these figures, as you seem to scrape the Gesundheitsamt of the counties, this would give you the numbers consolidated on state level.


Baden-Württemberg
Link to XLSX below the map
https://sozialministerium.baden-wuerttemberg.de/de/gesundheit-pflege/gesundheitsschutz/infektionsschutz-hygiene/informationen-zu-coronavirus/

Bayern
Numbers in an HTML table 
https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/index.htm

Berlin
Nur als Bild ?
https://www.berlin.de/sen/gpg/service/presse/2020/pressemitteilung.906973.php

Brandenburg
https://msgiv.brandenburg.de/msgiv/de/presse/pressemitteilungen/detail/~12-03-2020-30-corona-faelle-in-brandenburg

Bremen
https://www.senatspressestelle.bremen.de/detail.php?gsid=bremen146.c.331858.de&asl=bremen02.c.732.de

Hamburg
https://www.hamburg.de/coronavirus/

Hessen
https://soziales.hessen.de/gesundheit/infektionsschutz/coronavirus-sars-cov-2/taegliche-uebersicht-der-bestaetigten-sars-cov-2-faelle-hessen

Mecklenburg-Vorpommern
Bisher keine Pressemitteilungen / Fallzahlen gefunden:

Niedersachsen
https://www.niedersachsen.de/Coronavirus

Nordrhein-Westfalen
https://www.mags.nrw/coronavirus-fallzahlen-nrw

Rheinland-Pfalz
https://msagd.rlp.de/de/unsere-themen/gesundheit-und-pflege/gesundheitliche-versorgung/oeffentlicher-gesundheitsdienst-hygiene-und-infektionsschutz/infektionsschutz/informationen-zum-coronavirus-sars-cov-2/

Saarland
Bisher keine Pressemitteilungen / Fallzahlen gefunden:

Sachsen
https://www.sms.sachsen.de/coronavirus.html

Sachsen-Anhalt
https://verbraucherschutz.sachsen-anhalt.de/hygiene/infektionsschutz/infektionskrankheiten/coronavirus/

Schleswig-Holstein
https://www.schleswig-holstein.de/DE/Landesregierung/VIII/Presse/PI/2020/200313_VIII_Corona_tabelle.html

Thüringen
keine tabellarische Übersicht 
https://www.tmasgff.de/covid-19


Statista Übersicht für Deutschland
https://de.statista.com/statistik/daten/studie/1100750/umfrage/fallzahl-des-coronavirus-covid-19-nach-bundeslaendern/

**Comment by jgehrcke** [comment]
Also confer https://github.com/jgehrcke/covid-19-germany-gae/issues/58

**Comment by ndeuma** [comment]
We have been working on a project for providing county ("Landkreis") data since the #WirVsVirus hackathon. I'm only the frontend guy, but you can find links to the other repositories on the entry page here. 
https://github.com/ndeuma/covid19-casedata

**Comment by stefan123t** [comment]
Dear Niklas,
I have been able to compose a map from BKG and City of Berlin which matches the data released everyday by RKI through ARCGIS. Those maps are now on the Datawrapper River, but I would need to update the CSV source daily from ARCHIS as it is done with the other maps on that page ?
Feel free to reuse the Geojson giving reference to BKG and Berlin as well as data courtesy of RKI/ArcGIS.
Kind regards,
Stefan

cases and cases per 100k https://river.datawrapper.de/#popup/ASPdN https://river.datawrapper.de/#popup/0AEpL

deaths and death rate https://river.datawrapper.de/#popup/YeEOY https://river.datawrapper.de/#popup/lytZ4

**Comment by jgehrcke** [comment]
Discussion can of course continue, but I close this issue because the underlying task tracked here is done.

Feel free to consume:

https://github.com/jgehrcke/covid-19-germany-gae/blob/master/deaths-rki-by-state.csv
https://github.com/jgehrcke/covid-19-germany-gae/blob/master/deaths-rki-by-ags.csv
https://github.com/jgehrcke/covid-19-germany-gae/blob/master/cases-rki-by-state.csv
https://github.com/jgehrcke/covid-19-germany-gae/blob/master/cases-rki-by-ags.csv
