### ISSUE TITLE
deaths num

### ISSUE THREAD

**Issue by WhoIAmm** [jgehrcke/covid-19-germany-gae#75]
Could you please provide deaths num in cases-rki-by-ags.csv like you do in data.csv ? That would be very helpful.

**Comment by jgehrcke** [comment]
Hey, thanks for feedback. Planning to do that!

Just not yet sure how. Don't want to break current consumers, so I add new columns to  `cases-rki-by-ags.csv` or add a new file.

**Comment by WhoIAmm** [comment]
> Hey, thanks for feedback. Planning to do that!
> 
> Just not yet sure how. Don't want to break current consumers, so I add new columns to `cases-rki-by-ags.csv` or add a new file.

That would be great, I'm looking forward to see that, thanks a lot.

**Comment by jgehrcke** [comment]
Done in https://github.com/jgehrcke/covid-19-germany-gae/pull/76

See 
- https://github.com/jgehrcke/covid-19-germany-gae/blob/master/deaths-rki-by-ags.csv 
- https://github.com/jgehrcke/covid-19-germany-gae/blob/master/deaths-rki-by-state.csv

**Comment by jgehrcke** [comment]
@WhoIAmm let me know what you think, thanks!
