### ISSUE TITLE
New data, rki.

### ISSUE THREAD

**Issue by WhoIAmm** [jgehrcke/covid-19-germany-gae#98]
What's wrong with rki data, Both death and confirm? It's not updating, thank you a lot, it would be very helpful.

**Comment by jgehrcke** [comment]
Hey @WhoIAmm may I direct you to the discussion in https://github.com/jgehrcke/covid-19-germany-gae/issues/93 and then maybe ask you to come back with little more specific description of what you're asking for?

**Comment by jgehrcke** [comment]
Closing this for now. Would still appreciate your feedback @WhoIAmm!
